[package]
name = "rpm-qa"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
camino = "1"
cap-std = { version = "3", default-features = false, features = ["fs_utf8"] }
rustix = { version = "1", features = ["fs"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
tempfile = "3"
